<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Verify.Xunit" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Csharp2Md.Analysis\Csharp2Md.Analysis.csproj" />
    <ProjectReference Include="..\..\src\Csharp2Md.Storage\Csharp2Md.Storage.csproj" />
    <ProjectReference Include="..\..\src\Csharp2Md.Projection\Csharp2Md.Projection.csproj" />
    <ProjectReference Include="..\..\src\Csharp2Md.Cli\Csharp2Md.Cli.csproj" />
  </ItemGroup>

</Project>
