namespace Csharp2Md.Core.Facts.Metadata;

internal static class GeneratedOrigin
{
    public static bool Detect(string? source) =>
        source is not null
        && source.AsSpan().TrimStart().StartsWith("// <auto-generated", StringComparison.OrdinalIgnoreCase);
}
