using System.Text.Json.Serialization;

namespace Csharp2Md.Storage.Wire;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    WriteIndented = true,
    IndentSize = 2,
    NewLine = "\n")]
[JsonSerializable(typeof(FactReferenceDto))]
[JsonSerializable(typeof(StructuralLiteralDto))]
[JsonSerializable(typeof(PayloadEntryDto))]
[JsonSerializable(typeof(ObservationIdentityDto))]
[JsonSerializable(typeof(SourceSpanDto))]
[JsonSerializable(typeof(EvidenceLocatorDto))]
[JsonSerializable(typeof(DeclarationLocatorDto))]
[JsonSerializable(typeof(BindingDiagnosticDto))]
[JsonSerializable(typeof(FacetBindingEntryDto))]
[JsonSerializable(typeof(ProofAgentIdentityDto))]
[JsonSerializable(typeof(SolutionDto))]
[JsonSerializable(typeof(ProjectDto))]
[JsonSerializable(typeof(DocumentDto))]
[JsonSerializable(typeof(SymbolDto))]
[JsonSerializable(typeof(ComponentDto))]
[JsonSerializable(typeof(DeploymentUnitDto))]
[JsonSerializable(typeof(EntryPointDto))]
[JsonSerializable(typeof(BoundaryOperationDto))]
[JsonSerializable(typeof(ExternalSystemDto))]
[JsonSerializable(typeof(ContractDto))]
[JsonSerializable(typeof(ContractBindingDto))]
[JsonSerializable(typeof(ContractRevisionDto))]
[JsonSerializable(typeof(DataStoreDto))]
[JsonSerializable(typeof(DataObjectDto))]
[JsonSerializable(typeof(DataFieldDto))]
[JsonSerializable(typeof(DataOperationDto))]
[JsonSerializable(typeof(ConfigurationBindingDto))]
[JsonSerializable(typeof(ObservationDto))]
[JsonSerializable(typeof(ConfirmedRelationDto))]
[JsonSerializable(typeof(CandidateLinkDto))]
[JsonSerializable(typeof(UnresolvedRecordDto))]
[JsonSerializable(typeof(OpenFrontierDto))]
[JsonSerializable(typeof(ManifestEnvelope))]
[JsonSerializable(typeof(ManifestEntry))]
[JsonSerializable(typeof(CoverageMetricDto))]
[JsonSerializable(typeof(CoverageEnvelope))]
[JsonSerializable(typeof(RunCertificationEnvelope))]
[JsonSerializable(typeof(DiagnosticRecordDto))]
[JsonSerializable(typeof(DiagnosticsEnvelope))]
[JsonSerializable(typeof(QuarantineRecordDto))]
[JsonSerializable(typeof(QuarantineEnvelope))]
[JsonSerializable(typeof(MeasurementRecordDto))]
[JsonSerializable(typeof(MeasurementsEnvelope))]
[JsonSerializable(typeof(RedactionEnvelopeDto))]
[JsonSerializable(typeof(CatalogEntryDto))]
[JsonSerializable(typeof(ImmutableArray<CatalogEntryDto>))]
[JsonSerializable(typeof(ImmutableArray<SourceSpanDto>))]
[JsonSerializable(typeof(StructuralFactsShard))]
[JsonSerializable(typeof(ArchitectureFactsShard))]
[JsonSerializable(typeof(ContractFactsShard))]
[JsonSerializable(typeof(PersistenceFactsShard))]
[JsonSerializable(typeof(ConfigurationFactsShard))]
[JsonSerializable(typeof(ImmutableArray<FactReferenceDto>))]
[JsonSerializable(typeof(ImmutableArray<PayloadEntryDto>))]
[JsonSerializable(typeof(ImmutableArray<FacetBindingEntryDto>))]
[JsonSerializable(typeof(ImmutableArray<ObservationIdentityDto>))]
[JsonSerializable(typeof(ImmutableArray<string>))]
[JsonSerializable(typeof(ImmutableArray<ManifestEntry>))]
[JsonSerializable(typeof(ImmutableArray<DiagnosticRecordDto>))]
[JsonSerializable(typeof(ImmutableArray<QuarantineRecordDto>))]
[JsonSerializable(typeof(ImmutableArray<MeasurementRecordDto>))]
[JsonSerializable(typeof(ImmutableArray<ObservationDto>))]
[JsonSerializable(typeof(ImmutableArray<ConfirmedRelationDto>))]
[JsonSerializable(typeof(ImmutableArray<CandidateLinkDto>))]
[JsonSerializable(typeof(ImmutableArray<UnresolvedRecordDto>))]
[JsonSerializable(typeof(ImmutableArray<OpenFrontierDto>))]
[JsonSerializable(typeof(ImmutableArray<SolutionDto>))]
[JsonSerializable(typeof(ImmutableArray<ProjectDto>))]
[JsonSerializable(typeof(ImmutableArray<DocumentDto>))]
[JsonSerializable(typeof(ImmutableArray<SymbolDto>))]
[JsonSerializable(typeof(ImmutableArray<ComponentDto>))]
[JsonSerializable(typeof(ImmutableArray<DeploymentUnitDto>))]
[JsonSerializable(typeof(ImmutableArray<EntryPointDto>))]
[JsonSerializable(typeof(ImmutableArray<BoundaryOperationDto>))]
[JsonSerializable(typeof(ImmutableArray<ExternalSystemDto>))]
[JsonSerializable(typeof(ImmutableArray<ContractDto>))]
[JsonSerializable(typeof(ImmutableArray<ContractBindingDto>))]
[JsonSerializable(typeof(ImmutableArray<ContractRevisionDto>))]
[JsonSerializable(typeof(ImmutableArray<DataStoreDto>))]
[JsonSerializable(typeof(ImmutableArray<DataObjectDto>))]
[JsonSerializable(typeof(ImmutableArray<DataFieldDto>))]
[JsonSerializable(typeof(ImmutableArray<DataOperationDto>))]
[JsonSerializable(typeof(ImmutableArray<ConfigurationBindingDto>))]
public partial class StorageJsonContext : JsonSerializerContext;
