using System.Text.Json.Serialization;

namespace Csharp2Md.Storage.Wire;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    WriteIndented = true,
    IndentSize = 2,
    NewLine = "\n")]
[JsonSerializable(typeof(FactReferenceDto))]
[JsonSerializable(typeof(StructuralLiteralDto))]
[JsonSerializable(typeof(PayloadEntryDto))]
[JsonSerializable(typeof(ObservationIdentityDto))]
[JsonSerializable(typeof(SourceSpanDto))]
[JsonSerializable(typeof(EvidenceLocatorDto))]
[JsonSerializable(typeof(BindingDiagnosticDto))]
[JsonSerializable(typeof(FacetBindingEntryDto))]
[JsonSerializable(typeof(ProofAgentIdentityDto))]
[JsonSerializable(typeof(SolutionDto))]
[JsonSerializable(typeof(ProjectDto))]
[JsonSerializable(typeof(DocumentDto))]
[JsonSerializable(typeof(SymbolDto))]
[JsonSerializable(typeof(ComponentDto))]
[JsonSerializable(typeof(DeploymentUnitDto))]
[JsonSerializable(typeof(EntryPointDto))]
[JsonSerializable(typeof(BoundaryOperationDto))]
[JsonSerializable(typeof(ExternalSystemDto))]
[JsonSerializable(typeof(ContractDto))]
[JsonSerializable(typeof(ContractBindingDto))]
[JsonSerializable(typeof(ContractRevisionDto))]
[JsonSerializable(typeof(DataStoreDto))]
[JsonSerializable(typeof(DataObjectDto))]
[JsonSerializable(typeof(DataFieldDto))]
[JsonSerializable(typeof(DataOperationDto))]
[JsonSerializable(typeof(ConfigurationBindingDto))]
[JsonSerializable(typeof(ObservationDto))]
[JsonSerializable(typeof(ConfirmedRelationDto))]
[JsonSerializable(typeof(CandidateLinkDto))]
[JsonSerializable(typeof(UnresolvedRecordDto))]
[JsonSerializable(typeof(OpenFrontierDto))]
[JsonSerializable(typeof(ManifestEnvelope))]
[JsonSerializable(typeof(ManifestEntry))]
[JsonSerializable(typeof(CoverageMetricDto))]
[JsonSerializable(typeof(CoverageEnvelope))]
[JsonSerializable(typeof(RunCertificationEnvelope))]
[JsonSerializable(typeof(DiagnosticRecordDto))]
[JsonSerializable(typeof(DiagnosticsEnvelope))]
[JsonSerializable(typeof(QuarantineRecordDto))]
[JsonSerializable(typeof(QuarantineEnvelope))]
[JsonSerializable(typeof(MeasurementRecordDto))]
[JsonSerializable(typeof(MeasurementsEnvelope))]
[JsonSerializable(typeof(ImmutableArray<FactReferenceDto>))]
[JsonSerializable(typeof(ImmutableArray<PayloadEntryDto>))]
[JsonSerializable(typeof(ImmutableArray<FacetBindingEntryDto>))]
[JsonSerializable(typeof(ImmutableArray<ObservationIdentityDto>))]
[JsonSerializable(typeof(ImmutableArray<string>))]
[JsonSerializable(typeof(ImmutableArray<ManifestEntry>))]
[JsonSerializable(typeof(ImmutableArray<DiagnosticRecordDto>))]
[JsonSerializable(typeof(ImmutableArray<QuarantineRecordDto>))]
[JsonSerializable(typeof(ImmutableArray<MeasurementRecordDto>))]
public partial class StorageJsonContext : JsonSerializerContext;
