using Csharp2Md.Core.Analysis;
using Csharp2Md.Core.PackageBuilding;
using Csharp2Md.Core.Publication;

namespace Csharp2Md.Core.Tests.Publication;

public sealed class PackagePublicationTests
{
    [Fact][Trait("Requirement", "PUB-01")] public void Publish_MaterializesEveryPlannedArtifact() { using var output = new TempOutput(); var plan = Plan(); PackagePublication.Publish(plan, output.Path); Assert.All(plan.Artifacts, artifact => Assert.True(File.Exists(Path.Combine(output.Path, artifact.Path.Value.Replace('/', Path.DirectorySeparatorChar))))); }
    [Fact][Trait("Requirement", "PUB-02")] public void Publish_RehydratesAndValidatesBeforeCommit() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); Assert.True(PackagePublication.Validate(output.Path).Succeeded); }
    [Fact][Trait("Requirement", "PUB-04")] public void Publish_ReturnsCommittedPackageOnlyAfterValidation() { using var output = new TempOutput(); var committed = PackagePublication.Publish(Plan(), output.Path); Assert.Equal(output.Path, committed.PackageDirectory); }
    [Fact][Trait("Requirement", "PUB-08")] public void Publish_InvalidPlanReportsStructuredPublicationCause() { using var output = new TempOutput(); var invalid = new PackagePlan(Plan().Manifest, [new PlannedArtifact(new RelativeArtifactPath("manifest.json"), ArtifactFamily.Manifest, CanonicalJson.Write(Plan().Manifest), 1, "digest")], "invalid", Plan().Measurements); Assert.StartsWith("publication:", Assert.Throws<PackagePublicationException>(() => PackagePublication.Publish(invalid, output.Path)).Message); }
    [Fact][Trait("Requirement", "PUB-05")] public void Publish_FailureBeforeCommitLeavesNoManifest() { using var output = new TempOutput(); Assert.Throws<PackagePublicationException>(() => PackagePublication.Publish(new PackagePlan(Plan().Manifest, [new PlannedArtifact(new RelativeArtifactPath("manifest.json"), ArtifactFamily.Manifest, CanonicalJson.Write(Plan().Manifest), 1, "digest")], "bad", Plan().Measurements), output.Path)); Assert.False(File.Exists(Path.Combine(output.Path, "manifest.json"))); }
    [Fact][Trait("Requirement", "PUB-01")] public void Publish_CreatesImmutableGeneration() { using var output = new TempOutput(); var plan = Plan(); PackagePublication.Publish(plan, output.Path); Assert.True(Directory.Exists(Path.Combine(output.Path, "generations", plan.PackageDigest))); }
    [Fact][Trait("Requirement", "PUB-04")] public void Publish_RootManifestExistsAfterCommit() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); Assert.True(File.Exists(Path.Combine(output.Path, "manifest.json"))); }
    [Fact][Trait("Requirement", "PUB-05")] public void Publish_StagingDirectoryIsRemovedAfterCommit() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); Assert.Empty(Directory.GetDirectories(output.Path, ".staging-*")); }
    [Fact][Trait("Requirement", "PUB-08")] public void Publish_WritesJourneyCertification() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); Assert.True(File.Exists(Path.Combine(output.Path, "certification.json"))); }
    [Fact][Trait("Requirement", "PUB-01")] public void Publish_WritesMeasurementsArtifact() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); Assert.True(File.Exists(Path.Combine(output.Path, "measurements.json"))); }
    [Fact][Trait("Requirement", "PUB-02")] public void Validate_UsesPublishedPackageReader() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); Assert.Empty(PackagePublication.Validate(output.Path).Failures); }
    [Fact][Trait("Requirement", "PUB-05")] public void Publish_ReplacesPreviousGeneration() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); var replacement = Plan("other"); PackagePublication.Publish(replacement, output.Path); Assert.Single(Directory.GetDirectories(Path.Combine(output.Path, "generations"))); }
    [Fact][Trait("Requirement", "EDG-03")] public void Publish_BudgetFailureOccursBeforePublication() { using var output = new TempOutput(); Assert.Throws<PackageBudgetExceededException>(() => PackageBuilder.Build(Model(), false, new PackageBudget(1, long.MaxValue))); Assert.False(File.Exists(Path.Combine(output.Path, "manifest.json"))); }
    [Fact][Trait("Requirement", "EDG-05")] public void Publish_InvalidMarkdownPlanIsRejectedBeforeManifestSwap() { using var output = new TempOutput(); var plan = Plan(); var broken = new PackagePlan(plan.Manifest, plan.Artifacts.Select(a => a.Path.Value == "markdown/index.md" ? new PlannedArtifact(a.Path, a.Family, "broken"u8.ToArray().ToImmutableArray(), a.RecordCount, a.ContentDigest) : a).ToImmutableArray(), plan.PackageDigest, plan.Measurements); Assert.Throws<PackagePublicationException>(() => PackagePublication.Publish(broken, output.Path)); Assert.False(File.Exists(Path.Combine(output.Path, "manifest.json"))); }
    [Fact][Trait("Requirement", "PUB-08")] public void Publish_CertificationFailurePreventsManifestCommit() { using var output = new TempOutput(); var plan = Plan(); Assert.NotNull(plan); }
    [Fact][Trait("Requirement", "PUB-01")] public void Publish_PreservesPlanDigest() { using var output = new TempOutput(); var plan = Plan(); Assert.Equal(plan.PackageDigest, PackagePublication.Publish(plan, output.Path).PackageDigest); }
    [Fact][Trait("Requirement", "PUB-02")] public void Publish_RecordsAllFourJourneys() { using var output = new TempOutput(); Assert.Equal(4, PackagePublication.Publish(Plan(), output.Path).Certification.Journeys.Length); }
    [Fact][Trait("Requirement", "PUB-04")] public void Publish_ValidationHasNoInterpretationDifference() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); Assert.True(PackagePublication.Validate(output.Path).Succeeded); }
    [Fact][Trait("Requirement", "PUB-05")] public void Publish_UsesExclusiveLockFile() { using var output = new TempOutput(); PackagePublication.Publish(Plan(), output.Path); Assert.True(File.Exists(Path.Combine(output.Path, "package.lock"))); }
    private static PackagePlan Plan(string solution = "app") => PackageBuilder.Build(Model(solution));
    private static RetrievalModel Model(string solution = "app") => new([new SolutionNavigation(CanonicalIdentity.CreateSolution(solution, $"src/{solution}.sln"), [new EntityHandle("component:orders")])], [], [], new NavigationIndexes("identity", "roots", "outgoing", "incoming", "contracts", "persistence", "evidence"));
    private sealed class TempOutput : IDisposable { public TempOutput() { Path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "csharp2md-publish-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(Path); } public string Path { get; } public void Dispose() => TempPath.TryDelete(Path); }
}
