using Csharp2Md.Core.Facts.Identity;
using Csharp2Md.Core.Facts.Metadata;
using Csharp2Md.Core.Facts.Model;

namespace Csharp2Md.Core.Tests.Facts.Metadata;

public sealed class GeneratedOriginTests
{
    private static readonly ProjectFactId Project = ProjectFactId.Create("src/App/App.csproj");
    private static readonly DocumentFactId Document = DocumentFactId.Create(Project, "Features/Generated.cs");

    [Theory]
    [InlineData("// <auto-generated>\nnamespace Generated;", true)]
    [InlineData("// <AUTO-GENERATED>\nnamespace Generated;", true)]
    [InlineData("namespace HandWritten;\n// <auto-generated>", false)]
    [InlineData(null, false)]
    public void Detect_SourceHeader_ReturnsExpectedGeneratedOrigin(string? source, bool expected) =>
        Assert.Equal(expected, GeneratedOrigin.Detect(source));

    [Fact]
    public void HeaderAndEvidence_ExplicitGeneratedOrigin_DoesNotChangeFactIdentity()
    {
        var factId = Document.ToFactId();
        var generatedHeader = FactHeader.Create(factId, FactKind.Document, FactResolution.Syntactic, generatedOrigin: true);
        var ordinaryHeader = FactHeader.Create(factId, FactKind.Document, FactResolution.Syntactic);
        var evidence = new Evidence(Document, "Features/Generated.cs", 1, 1, 1, 20, generatedOrigin: true);

        Assert.True(generatedHeader.GeneratedOrigin);
        Assert.False(ordinaryHeader.GeneratedOrigin);
        Assert.Equal(factId, generatedHeader.Id);
        Assert.Equal(factId, ordinaryHeader.Id);
        Assert.True(evidence.GeneratedOrigin);
    }

    [Fact]
    public void HeaderAndEvidence_OmittedGeneratedOrigin_DefaultToNotDetected()
    {
        var header = FactHeader.Create(Document.ToFactId(), FactKind.Document, FactResolution.Syntactic);
        var evidence = new Evidence(Document, "Features/Generated.cs", 1, 1, 1, 20);

        Assert.False(header.GeneratedOrigin);
        Assert.False(evidence.GeneratedOrigin);
    }
}
