namespace Csharp2Md.Core.Topic;

/// <summary>
/// Writes <c>raw/topic.yaml</c> (WIKI-10) and <c>raw/CLAUDE.md</c> (WIKI-11) — the two files that
/// describe the topic itself rather than any one analyzed source file.
/// </summary>
public static class TopicScaffoldWriter
{
    public const string TopicYamlFileName = "topic.yaml";
    public const string ClaudeMdFileName = "CLAUDE.md";

    /// <summary>
    /// <paramref name="options"/>'s <c>Topic</c> value doubles as both <c>slug</c> and <c>title</c>:
    /// it is already the human-facing name the caller chose via <c>--topic</c> (or its derived
    /// default), and nothing in WIKI-10 defines a further transformation from slug to a distinct
    /// title. <paramref name="toolVersion"/> is the packaged tool's version, reused verbatim in
    /// <c>CLAUDE.md</c>'s ingestion-source note.
    /// </summary>
    public static void Write(string outputRoot, TopicOptions options, string toolVersion)
    {
        ArgumentNullException.ThrowIfNull(outputRoot);
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(toolVersion);

        var rawRoot = TopicLayout.RawRoot(outputRoot);
        Directory.CreateDirectory(rawRoot);

        File.WriteAllText(Path.Combine(rawRoot, TopicYamlFileName), TopicYamlContent(options));
        File.WriteAllText(Path.Combine(rawRoot, ClaudeMdFileName), ClaudeMdContent(options, toolVersion));
    }

    // slug/title are always plain slug characters (TopicOptions.Create rejects anything else per
    // WIKI-14), so no YAML quoting/escaping is needed here the way FrontmatterYaml needs it for
    // source-derived titles.
    private static string TopicYamlContent(TopicOptions options) =>
        $"""
        slug: {options.Topic}
        title: {options.Topic}
        description: This topic was generated by csharp2md.

        """;

    private static string ClaudeMdContent(TopicOptions options, string toolVersion) =>
        $"""
        # {options.Topic}

        This topic was generated by `csharp2md` (version {toolVersion}), a tool that renders a
        C#/.NET codebase into a structured, LLM- and human-readable Markdown wiki.

        ## Frontmatter schema

        Every generated `.md` file under `raw/codebase/` carries a YAML frontmatter block with these
        fields: `title`, `source_kind`, `source_path`, `domain`, `topic`, `language`, `file_type`,
        `tags`, `created_by`, `source_service`, `analysis_status`. The published contract is
        `schemas/frontmatter.schema.json`.

        ## Directory conventions

        - `raw/codebase/` mirrors the analyzed codebase's folder structure: one `.md` file per source
          file, plus an `index.md` per directory level.
        - `raw/dependencies.json` and `raw/dependencies.mmd` hold the detected dependency graph.
        - `raw/topic.yaml` and `raw/CLAUDE.md` (this file) describe the topic itself.
        - `raw/log.md` records the run that produced this topic.

        ## Phase 2

        `source_service` and `analysis_status` are placeholders in this Phase 1 output. Phase 2
        resolves them by rewriting frontmatter once service-level graph resolution is implemented.

        """;
}
