using Csharp2Md.Core.Analysis;
using Csharp2Md.Core.Analysis.Contracts;
using Csharp2Md.Core.Facts.Serialization;
using Csharp2Md.Core.Tests.Pipeline;
using Csharp2Md.Core.Topic;

namespace Csharp2Md.Core.Tests.Analysis;

/// <summary>
/// T14: proves <c>RelationCollector.Refine</c> is wired into
/// <c>TrustedSemanticProjectProcessor.BindDocuments</c> - the same relations T12 proved in
/// syntax-only mode survive (at least) at <c>Syntactic</c> resolution once real semantic binding
/// runs, and the fixture's own genuine unresolved-cross-project-type case
/// (<c>Acme.Payments/PaymentsService.cs</c>'s <c>Payments.PaymentsBase</c>, generated by gRPC
/// tooling this pipeline never runs) still yields the syntax-only baseline relation instead of
/// nothing - RELC-08 proven end-to-end, not just at the <c>RelationCollector</c> unit level.
/// </summary>
[Trait("Category", "Integration")]
public sealed class RelationCollectorTrustedWiringTests(RelationCollectorTrustedWiringFixture fixture)
    : IClassFixture<RelationCollectorTrustedWiringFixture>
{
    [Fact]
    public void AnalyzeAsync_TrustedMode_RunsAsSemanticAndSucceeds()
    {
        Assert.Equal(0, fixture.Result.ExitCode);
        Assert.Equal(AnalysisMode.Semantic, fixture.Result.EffectiveMode);
    }

    [Fact]
    public void AnalyzeAsync_TrustedMode_EveryRelationKindT12ProvedInSyntaxOnlyMode_StaysAtLeastSyntactic()
    {
        var payments = fixture.FindDocumentFragment("PaymentsService.cs");
        var orders = fixture.FindDocumentFragment("OrderService.cs");

        AssertAtLeastSyntactic(payments, "subscribes");
        AssertAtLeastSyntactic(payments, "handles");
        AssertAtLeastSyntactic(payments, "publishes");
        AssertAtLeastSyntactic(payments, "inherits");
        AssertAtLeastSyntactic(orders, "http-client");
        AssertAtLeastSyntactic(orders, "calls");
    }

    [Fact]
    public void AnalyzeAsync_TrustedMode_UnresolvedCrossProjectBaseType_StillYieldsSyntaxOnlyBaselineRelation()
    {
        var payments = fixture.FindDocumentFragment("PaymentsService.cs");

        var inheritsRelation = Assert.Single(payments.Relations, relation => relation.RelationKind == "inherits");
        Assert.Contains(inheritsRelation.Details!.Value, detail =>
            detail.Key == "target_text" && detail.Value is "PaymentsBase" or "Payments.PaymentsBase");
        Assert.Null(inheritsRelation.TargetId);
        Assert.False(string.IsNullOrWhiteSpace(inheritsRelation.UnresolvedReason));
    }

    private static void AssertAtLeastSyntactic(FactualJsonDocument document, string relationKind)
    {
        var matches = document.Relations.Where(relation => relation.RelationKind == relationKind).ToArray();
        Assert.NotEmpty(matches);
        Assert.All(matches, relation => Assert.NotEqual("unresolved", relation.Header.Resolution));
    }
}

/// <summary>
/// T14, standalone: proves the T13 "PublishAsync through a variable" inference case (the syntax-only
/// pass finds no candidate at all for this shape) actually flows through the real
/// <c>TrustedSemanticProjectProcessor.BindDocuments</c> wiring end-to-end, not just via a direct
/// <c>RelationCollector.Refine</c> unit call. Self-contained (no external package references) so
/// real MSBuild evaluation and compilation are fast and deterministic.
/// </summary>
[Trait("Category", "Integration")]
public sealed class RelationCollectorTrustedRefinementWiringTests : IDisposable
{
    private readonly string _input = Directory.CreateTempSubdirectory("csharp2md-relc-trusted-refine-input-").FullName;
    private readonly string _output = Path.Combine(Path.GetTempPath(), $"csharp2md-relc-trusted-refine-output-{Guid.NewGuid():N}");

    public void Dispose()
    {
        Directory.Delete(_input, recursive: true);
        if (Directory.Exists(_output))
        {
            Directory.Delete(_output, recursive: true);
        }
    }

    [Fact]
    public async Task AnalyzeAsync_TrustedMode_PublishAsyncThroughAVariable_ResolvesTargetTextThroughTheRealPipeline()
    {
        var directory = Path.Combine(_input, "App");
        Directory.CreateDirectory(directory);
        File.WriteAllText(Path.Combine(directory, "App.csproj"),
            "<Project Sdk=\"Microsoft.NET.Sdk\"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup></Project>");
        File.WriteAllText(Path.Combine(directory, "Worker.cs"), """
            using System.Threading;
            using System.Threading.Tasks;

            public sealed record PaymentProcessed(System.Guid PaymentId);

            public interface IEventBus
            {
                Task PublishAsync<TEvent>(TEvent message, CancellationToken cancellationToken = default);
            }

            public sealed class Worker(IEventBus bus)
            {
                public async Task RunAsync()
                {
                    var message = new PaymentProcessed(System.Guid.NewGuid());
                    await bus.PublishAsync(message);
                }
            }
            """);

        var request = Assert.IsType<AnalysisRequest>(AnalysisRequest.Create(
            _input, _output,
            options: new AnalysisOptions { Mode = AnalysisMode.Semantic, Trust = TrustMode.TrustedSolution }).Request);
        var result = await new AnalysisEngine().AnalyzeAsync(request);

        Assert.Equal(0, result.ExitCode);
        Assert.Equal(AnalysisMode.Semantic, result.EffectiveMode);

        var documentRoot = Path.Combine(TopicLayout.RawRoot(_output), "facts", "document");
        var fragment = Directory.EnumerateFiles(documentRoot, "*.json", SearchOption.AllDirectories)
            .Select(path => FactualJsonSerializer.Deserialize(File.ReadAllBytes(path)))
            .Single(candidate => candidate.Documents.Length == 1
                && candidate.Documents[0].RelativePath.EndsWith("Worker.cs", StringComparison.Ordinal));

        // The syntax-only pass alone finds no "publishes" candidate for this call shape (no explicit
        // <T>, no object-creation argument) - only the real semantic-refinement wiring can produce it.
        var publish = Assert.Single(fragment.Relations, relation => relation.RelationKind == "publishes");
        Assert.Contains(publish.Details!.Value, detail => detail is { Key: "target_text", Value: "PaymentProcessed" });
    }
}

public sealed class RelationCollectorTrustedWiringFixture : IAsyncLifetime
{
    private static readonly string[] Projects =
        [SyntheticFixtureRun.Orders, SyntheticFixtureRun.Payments, SyntheticFixtureRun.SharedContracts];

    public string Output { get; } = Path.Combine(Path.GetTempPath(), $"csharp2md-relc-trusted-{Guid.NewGuid():N}");

    public AnalysisResult Result { get; private set; } = null!;

    public async Task InitializeAsync()
    {
        var manifestDirectory = Directory.CreateTempSubdirectory("csharp2md-relc-trusted-manifest-").FullName;
        var manifest = FixtureManifest.WriteOverrides(manifestDirectory, Projects);

        var request = Assert.IsType<AnalysisRequest>(AnalysisRequest.Create(
            manifest, Output,
            options: new AnalysisOptions { Mode = AnalysisMode.Semantic, Trust = TrustMode.TrustedSolution },
            topic: "acme-relation-trusted-wiring", domain: "system-design").Request);
        Result = await new AnalysisEngine().AnalyzeAsync(request);
        if (Result.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"fixture analysis failed with exit {Result.ExitCode}: {string.Join(" | ", Result.Diagnostics)}");
        }
    }

    public Task DisposeAsync()
    {
        if (Directory.Exists(Output))
        {
            Directory.Delete(Output, recursive: true);
        }

        return Task.CompletedTask;
    }

    public FactualJsonDocument FindDocumentFragment(string fileName)
    {
        var documentRoot = Path.Combine(TopicLayout.RawRoot(Output), "facts", "document");
        foreach (var path in Directory.EnumerateFiles(documentRoot, "*.json", SearchOption.AllDirectories))
        {
            var candidate = FactualJsonSerializer.Deserialize(File.ReadAllBytes(path));
            if (candidate.Documents.Length == 1
                && candidate.Documents[0].RelativePath.EndsWith(fileName, StringComparison.Ordinal))
            {
                return candidate;
            }
        }

        throw new InvalidOperationException($"No persisted document fragment found for {fileName}.");
    }
}
