<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Csharp2Md.Domain.Tests" />
    <InternalsVisibleTo Include="Csharp2Md.Storage" />
  </ItemGroup>

</Project>
