<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SistemaE.Validacao</RootNamespace>
    <AssemblyName>SistemaE.Validacao</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaE.Nucleo\SistemaE.Nucleo.csproj" />
    <ProjectReference Include="..\SistemaE.Infraestrutura\SistemaE.Infraestrutura.csproj" />
  </ItemGroup>
</Project>
