using Csharp2Md.Core.Topic;
using YamlDotNet.Serialization;

namespace Csharp2Md.Core.Tests.Topic;

/// <summary>WIKI-10/WIKI-11: <c>raw/topic.yaml</c> and <c>raw/CLAUDE.md</c>'s required content.</summary>
public sealed class TopicScaffoldWriterTests : IDisposable
{
    private static readonly IDeserializer Deserializer = new DeserializerBuilder().Build();

    private readonly string _outputRoot = Directory.CreateTempSubdirectory("csharp2md-scaffold-").FullName;

    public void Dispose() => Directory.Delete(_outputRoot, recursive: true);

    private static TopicOptions Options() => TopicOptions.Create("acme-shop", "system-design", "input-root").Options!;

    private string TopicYamlPath => Path.Combine(TopicLayout.RawRoot(_outputRoot), TopicScaffoldWriter.TopicYamlFileName);

    private string ClaudeMdPath => Path.Combine(TopicLayout.RawRoot(_outputRoot), TopicScaffoldWriter.ClaudeMdFileName);

    [Fact]
    public void Write_TopicYaml_ParsesAsYaml()
    {
        TopicScaffoldWriter.Write(_outputRoot, Options(), "2.0.0");

        var parsed = Deserializer.Deserialize<Dictionary<string, object>>(File.ReadAllText(TopicYamlPath));

        Assert.NotNull(parsed);
    }

    // WIKI-10: "containing slug (the --topic value), title, and a description stating the topic was
    // generated by csharp2md" — asserted against the parsed values, not just that the keys exist.
    [Fact]
    public void Write_TopicYaml_CarriesSlugTitleAndGeneratorDescription()
    {
        TopicScaffoldWriter.Write(_outputRoot, Options(), "2.0.0");

        var parsed = Deserializer.Deserialize<Dictionary<string, object>>(File.ReadAllText(TopicYamlPath));

        Assert.Equal("acme-shop", parsed["slug"]);
        Assert.Equal("acme-shop", parsed["title"]);
        Assert.Contains("csharp2md", (string)parsed["description"], StringComparison.Ordinal);
    }

    [Fact]
    public void Write_ClaudeMd_DocumentsTheGeneratorAndItsVersion()
    {
        TopicScaffoldWriter.Write(_outputRoot, Options(), "2.0.0");

        var content = File.ReadAllText(ClaudeMdPath);

        Assert.Contains("csharp2md", content, StringComparison.Ordinal);
        Assert.Contains("2.0.0", content, StringComparison.Ordinal);
    }

    // WIKI-11/WIKI-06: every field the Frontmatter Schema section defines must be named, so a reader
    // of CLAUDE.md never needs to open schemas/frontmatter.schema.json just to see the field list.
    [Fact]
    public void Write_ClaudeMd_DocumentsEveryFrontmatterSchemaField()
    {
        TopicScaffoldWriter.Write(_outputRoot, Options(), "2.0.0");

        var content = File.ReadAllText(ClaudeMdPath);

        Assert.All(
            [
                "title", "source_kind", "source_path", "domain", "topic", "language",
                "file_type", "tags", "created_by", "source_service", "analysis_status",
            ],
            field => Assert.Contains(field, content, StringComparison.Ordinal));
    }

    [Fact]
    public void Write_ClaudeMd_DocumentsTheDirectoryConventions()
    {
        TopicScaffoldWriter.Write(_outputRoot, Options(), "2.0.0");

        var content = File.ReadAllText(ClaudeMdPath);

        Assert.Contains("raw/codebase/", content, StringComparison.Ordinal);
        Assert.Contains("raw/dependencies.json", content, StringComparison.Ordinal);
        Assert.Contains("raw/dependencies.mmd", content, StringComparison.Ordinal);
        Assert.Contains("raw/log.md", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Write_ClaudeMd_NotesPhase2ResolvesSourceServiceAndAnalysisStatus()
    {
        TopicScaffoldWriter.Write(_outputRoot, Options(), "2.0.0");

        var content = File.ReadAllText(ClaudeMdPath);

        Assert.Contains("Phase 2", content, StringComparison.Ordinal);
        Assert.Contains("source_service", content, StringComparison.Ordinal);
        Assert.Contains("analysis_status", content, StringComparison.Ordinal);
    }

    [Fact]
    public void Write_BothFiles_LandUnderRawRoot()
    {
        TopicScaffoldWriter.Write(_outputRoot, Options(), "2.0.0");

        Assert.True(File.Exists(TopicYamlPath));
        Assert.True(File.Exists(ClaudeMdPath));
    }
}
