<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SistemaD.Aplicacao</RootNamespace>
    <AssemblyName>SistemaD.Aplicacao</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaD.Nucleo\SistemaD.Nucleo.csproj" />
    <ProjectReference Include="..\SistemaD.Infraestrutura\SistemaD.Infraestrutura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PacotePrivado.Parametros" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
