<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SistemaA.Infraestrutura</RootNamespace>
    <AssemblyName>SistemaA.Infraestrutura</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaA.Nucleo\SistemaA.Nucleo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>
</Project>
