<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>csharp2md</ToolCommandName>
    <PackageId>csharp2md</PackageId>
    <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Csharp2Md.Cli.Tests" />
    <InternalsVisibleTo Include="Csharp2Md.Analysis.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Csharp2Md.Analysis\Csharp2Md.Analysis.csproj" />
    <ProjectReference Include="..\Csharp2Md.Storage\Csharp2Md.Storage.csproj" />
    <ProjectReference Include="..\Csharp2Md.Projection\Csharp2Md.Projection.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
