using System.Globalization;
using System.Text;

namespace Csharp2Md.Analysis.Tests.Certification;

/// <summary>
/// GCPC-081: renders the engine-certification results as the versioned repository artifact at
/// <c>artifacts/verifications/engine-certification.md</c>. Not product surface (D-03): nothing under
/// <c>src/</c> references this type, and it is never invoked by the shipped CLI.
/// </summary>
internal static class EngineCertificationReportGenerator
{
    public static string Generate(ImmutableArray<(AreaCertificationResult Result, AreaCertificationVerdict Verdict)> entries)
    {
        var sb = new StringBuilder();
        sb.Append("# Engine Certification Report\n\n");
        sb.Append(
            "Measures classifier precision and recall against ground truth authored independently of\n" +
            "classifier output (GCPC-074..GCPC-076), per the normative thresholds in\n" +
            "`docs/architecture/quality-and-security.md`. Generated by the labeled-corpus certification\n" +
            "suite under `tests/Csharp2Md.Analysis.Tests/Certification/`, never by the shipped CLI --\n" +
            "engine certification is a repository test suite, not a command or a flag (D-03, GCPC-081).\n\n");
        sb.Append(
            "Regenerate: run `EngineCertificationReportGenerator.Generate` over a fresh " +
            "`EngineThresholds.Evaluate` result for every certified area and replace the table below. " +
            "`EngineCertificationReportTests` asserts the two never drift.\n\n");
        sb.Append("## Results\n\n");
        sb.Append("| Area | Precision | Recall | Precision threshold | Recall threshold | Verdict | Labeled items | Failing items |\n");
        sb.Append("| --- | ---: | ---: | ---: | ---: | --- | ---: | --- |\n");
        foreach (var (result, verdict) in entries.OrderBy(static e => e.Result.Area))
        {
            sb.Append("| ").Append(AreaName(verdict.Area))
              .Append(" | ").Append(FormatPercent(verdict.MeasuredPrecision))
              .Append(" | ").Append(FormatPercent(verdict.MeasuredRecall))
              .Append(" | ").Append(FormatPercent(verdict.PrecisionThreshold))
              .Append(" | ").Append(FormatPercent(verdict.RecallThreshold))
              .Append(" | ").Append(verdict.Verdict is CertificationVerdict.Pass ? "PASS" : "FAIL")
              .Append(" | ").Append(result.Measurements.Length)
              .Append(" | ").Append(verdict.FailingItems.IsEmpty
                  ? "-"
                  : string.Join(", ", verdict.FailingItems.Select(static item => item.Id)))
              .Append(" |\n");
        }

        return sb.ToString();
    }

    private static string AreaName(CertifiedArea area) => area switch
    {
        CertifiedArea.EntryPoint => "Entry points",
        CertifiedArea.LinkedCall => "Linked calls",
        CertifiedArea.Contract => "Contracts",
        CertifiedArea.Persistence => "Persistence",
        _ => throw new ArgumentOutOfRangeException(nameof(area), area, null),
    };

    private static string FormatPercent(double value) =>
        (value * 100).ToString("F2", CultureInfo.InvariantCulture) + "%";
}
