<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SistemaA.Aplicacao</RootNamespace>
    <AssemblyName>SistemaA.Aplicacao</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SistemaA.Infraestrutura\SistemaA.Infraestrutura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PacotePrivado.Parametros" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>
</Project>
